name       'garethr-elixir'
version    '0.0.1'
source     'git://github.com/garethr/garethr-elixir.git'
author     'Gareth Rushgrove'
license    'Apache License, Version 2.0'
summary    'Module for installing elixir on Ubuntu'

dependency 'puppetlabs/stdlib'
dependency 'garethr/erlang'
dependency 'maestrodev/wget'
